.PHONY: all demo smoke test sbom provenance

all: demo smoke test

demo:
	@echo "Running demo for poojakira..."

smoke:
	@echo "Running smoke tests for poojakira..."
	./smoke_test.sh

test:
	@echo "Running tests for poojakira..."
	pytest tests/

sbom:
	@echo "Generating SBOM using Syft..."
	syft dir:. -o cyclonedx-json > sbom.cdx.json
	@echo "SBOM generated: sbom.cdx.json"

provenance:
	@echo "SLSA provenance is generated by GitHub Actions using actions/attest-build-provenance."
	@echo "Local fake provenance is intentionally disabled."
	@exit 1
